# 파일을 저장할 디렉토리 설정
yts3:
  directory: images

# 서버 구성
server :
  # 서버가 실행될 포트 설정
  port : 8081

# Spring 데이터베이스 관련 설정
spring:
  datasource:
    # MariaDB JDBC 드라이버 클래스 지정
    driver-class-name: org.mariadb.jdbc.Driver
    # 데이터베이스 접속 URL 설정
    url: jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/yt_s3?allowMultiQueries=true
    # 데이터베이스 접속을 위한 사용자 이름 설정 (기본값: root)
    username: ${DB_USERNAME:root}
    # 데이터베이스 접속을 위한 암호 설정 (기본값: password)
    password: ${DB_PASSWORD:password}
  jwt:
    secret: ${JWT_KEY}
  servlet:
    multipart:
      # 업로드할 파일의 최대 크기 설정 (단일 파일 및 요청당 최대 크기)
      max-file-size: 50MB
      max-request-size: 50MB
  mvc:
    async:
      # 비동기 요청의 타임아웃 설정 (기본값: 5000ms)
      request-timeout: 5000

# MyBatis 설정
mybatis:
  # MyBatis가 사용할 클래스 별칭이 정의된 패키지
  type-aliases-package: com.uts3back
  # MyBatis 매퍼 XML 파일의 위치 지정
  mapper-locations: classpath:mapper/*.xml

MultipartFile:
  type: object
  properties:
    contentType:
      type: string
    size:
      type: integer
    file:
      type: string
      format: binary